### ISSUE TITLE
Files should not be bundled together when all files are assigned to different price options

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#178] opened 2017-09-04 15:15 UTC
This is perhaps an edge case but still a definite problem.

When a product has multiple files uploaded to it, Free Downloads automatically bundles those files into a single zip file in order to deliver one download file.

There is a problem with this, however. Free Downloads assumes that _all_ products with multiple files should have their files bundled together, but this isn't always the case. Take, for example, a product that has three files and three price options and each file is assigned to a different price option When a customer purchases this product they will only ever receive _one_ of the three files, yet Free Downloads still attempts to bundle all of the files together.

Here's an example product configuration that can be used to replicate the problem:
<img width="956" alt="screen shot 2017-09-04 at 10 15 08 am" src="https://user-images.githubusercontent.com/1034109/30032181-f82f9992-9159-11e7-85f6-beec060f463c.png">
<img width="966" alt="screen shot 2017-09-04 at 10 15 12 am" src="https://user-images.githubusercontent.com/1034109/30032182-f83fd8ca-9159-11e7-8002-24e57ccccf0d.png">

Since each of the files is assigned to a price option, no purchase nor free download should ever result in a bundled zip file.

**Comment by pippinsplugins** [comment] 2017-09-04 15:18
This is a blocker to testing #153

**Comment by ghost1227** [comment] 2017-09-05 01:14
@pippinsplugins Correction, I can't reproduce it. I did, however, find and fix a bug with Amazon and Dropbox hosted files. Do me a favor, pull issue/178, clear your download cache (uploads/edd-free-downloads-cache) and do a clean test. In my case, I had the zip cached from a previous test that intentionally downloaded all files, and thought I'd duplicated the issue. Once I removed the cached copy, it only downloaded the correct file.

**Comment by pippinsplugins** [comment] 2017-09-05 14:28
@ghost1227 can you please show me your product edit screen?

**Comment by ghost1227** [comment] 2017-09-05 17:06
<img width="765" alt="screen shot 2017-09-05 at 12 04 15 pm" src="https://user-images.githubusercontent.com/36433/30073139-617d03b6-9232-11e7-8ff0-f6a3147c3bd3.png">

"Purchasing" each price option only returns the referenced file. Also tested with a fifth product option set to 'all' and got a zip containing the file for the specific option, as well as the 'all' file.

**Comment by pippinsplugins** [comment] 2017-09-05 17:07
@ghost1227 try it again but with the 3rd or 4th price option set to 0.00 instead of the first price option.

**Comment by ghost1227** [comment] 2017-09-05 17:07
Roger, testing

**Comment by pippinsplugins** [comment] 2017-09-05 17:08
Note: when a file is assigned to a price option, that file should _always_ be downloaded as is and should not ever be put into a zip file.

**Comment by ghost1227** [comment] 2017-09-05 17:09
The zip only occurs if multiple files are set for a single price option (or all price options).

**Comment by ghost1227** [comment] 2017-09-05 17:09
Tested with this and got just the 5sec-gmaps-plugin.zip the is set for option 2.

<img width="775" alt="screen shot 2017-09-05 at 12 09 15 pm" src="https://user-images.githubusercontent.com/36433/30073341-12227700-9233-11e7-81e6-20f2e44f75c8.png">

**Comment by pippinsplugins** [comment] 2017-09-05 17:14
Is that on `master` or `issue/178`?

**Comment by ghost1227** [comment] 2017-09-05 17:15
`issue/178`, but should work the same on both. Nothing changed in the file selection process, just the download handler for Amazon/Dropbox files (on `master` they'd probably be zero-byte files right now, but it'd still only return the right files)

**Comment by pippinsplugins** [comment] 2017-09-05 17:16
Please test on master. I want to see you replicate the problem so we can doubly confirm that `issue/178` fixes it.

**Comment by pippinsplugins** [comment] 2017-09-05 17:16
Also please go ahead and open a PR for this/

**Comment by ghost1227** [comment] 2017-09-05 17:18
PR opened. tested on `master`, still unable to reproduce.

**Comment by ghost1227** [comment] 2017-09-05 17:18
Oops, didn't mean to hit close.

**Comment by SDavisMedia** [comment] 2017-09-05 20:42
So, my test results are messy. For the most part, I get the same results as @ghost1227. With the configuration you described, @pippinsplugins, I can't replicate. It seems to be working fine.

However, I did remember that I once opened a similar issue: https://github.com/easydigitaldownloads/edd-free-downloads/issues/160

That issue depends on Direct Download being enabled. So I enabled that with Pippin's configuration and still could not replicate. At this point, here was my simple configuration:

<img width="1026" alt="screenshot 2017-09-05 13 37 18" src="https://user-images.githubusercontent.com/2359131/30082358-60106ab0-923f-11e7-8221-94bfdf3e8618.png">

I then added one more file to see if the ordering of files made a difference. When I assigned this 3rd file to `All` price options, it bundled the product files together _BUT_ it bundled the first two files, instead of the second and third one, as you'd expect from this pic below:

<img width="1028" alt="screenshot 2017-09-05 13 39 53" src="https://user-images.githubusercontent.com/2359131/30082452-b6844b82-923f-11e7-89b5-19ff385185ea.png">

That resulted in:

<img width="422" alt="screenshot 2017-09-05 13 39 37" src="https://user-images.githubusercontent.com/2359131/30082459-be3f41ce-923f-11e7-81be-b944695159dc.png">

Notice one of those files is correct, but the other isn't. Note: If I were to assign that third file to the `Paid Option` price option, everything works.

So, I replicated a very similar problem. And I even just disabled Direct Download and still get the above behavior. So there's definitely a bug. But I can only replicate it with this configuration, not Pippin's.

**Comment by ghost1227** [comment] 2017-09-05 21:38
I still can't replicate... even following @SDavisMedia instructions.

**Comment by SDavisMedia** [comment] 2017-09-05 21:54
@ghost1227 just to be sure, are your price options and product files in the same exact order as mine above?

**Comment by ghost1227** [comment] 2017-09-05 21:57
@SDavisMedia I've tried several configurations, including copying yours exactly from the screenshots. No love.

**Comment by pippinsplugins** [comment] 2017-09-06 02:52
@ghost1227 please show a screenshot of your exact configuration while attempting to replicate the behavior Sean described.

**Comment by ghost1227** [comment] 2017-09-06 02:57
Current download and extension settings: 

<img width="770" alt="screen shot 2017-09-05 at 9 56 24 pm" src="https://user-images.githubusercontent.com/36433/30092549-2d69db3c-9285-11e7-95e6-7ea39cdacb9f.png">
<img width="1068" alt="screen shot 2017-09-05 at 9 56 42 pm" src="https://user-images.githubusercontent.com/36433/30092550-2d6b6592-9285-11e7-818e-22104e31299c.png">

Also tried several other configurations including matching his exactly.

**Comment by cklosowski** [comment] 2017-09-06 16:28
I cannot replicate this either. This was my configuration/testing. I had `Auto Download` on for testing.

First I setup this configuration, and all files were delivered correctly:
![screen shot 2017-09-06 at 9 25 03 am](https://user-images.githubusercontent.com/1390124/30123019-75cab21a-92e5-11e7-9e22-ff0126c9448a.png)

Then I added a 4th file, set to the `All` assignment, and it also worked:
![screen shot 2017-09-06 at 9 25 56 am](https://user-images.githubusercontent.com/1390124/30123053-8c8edfda-92e5-11e7-8b9e-419ad77b938b.png)

The results after it's un-compressed:
![screen shot 2017-09-06 at 9 27 29 am](https://user-images.githubusercontent.com/1390124/30123086-a8eb9998-92e5-11e7-8a3a-2c49be7307a3.png)

**Comment by cklosowski** [comment] 2017-09-06 16:29
Actually striek that, it *DID NOT WORK* correctly. it delivered the wrong file

**Comment by mintplugins** [comment] 2017-09-06 17:03
It appears to be working correctly for me on `master`. 

<img width="1049" alt="screen shot 2017-09-06 at 11 02 27 am" src="https://user-images.githubusercontent.com/1638128/30124597-e5103a84-92f2-11e7-98dd-e42a5d2eff15.png">

<img width="1052" alt="screen shot 2017-09-06 at 11 02 44 am" src="https://user-images.githubusercontent.com/1638128/30124614-f0e6c062-92f2-11e7-911d-1b8e723f90d5.png">

Result after downloading free files (unzipped result):
<img width="687" alt="screen shot 2017-09-06 at 11 01 08 am" src="https://user-images.githubusercontent.com/1638128/30124632-f6589278-92f2-11e7-9166-2fbbcfcedbca.png">

**Comment by cklosowski** [comment] 2017-09-06 18:52
There is another bug in here though. If you have TWO free price IDs and each of those get's a different file, and you include an All file, then it delivers from cache whichever one was delivered first.

Case:
Price ID 1 - Free
Price ID 2 - Free

File ID 1 - Assigned to price ID 1
File ID 2 - Assigned to price ID 2
File ID 3 - Assigned to all

Go 'purchase' Price ID 1 with caching enabled, and then try and purchase price ID 2, you'll get the same .zip file.

**Comment by SDavisMedia** [comment] 2017-09-06 19:23
The [above bug](https://github.com/easydigitaldownloads/edd-free-downloads/issues/178#issuecomment-327579540) confirmed fixed for me on `issue/184`.

**Comment by pippinsplugins** [comment] 2017-10-06 18:03
Punting to 2.3 for now.

**Comment by cklosowski** [comment] 2018-04-10 04:03
This seems to be resolved for me in the current `master`. @SDavisMedia you mind testing it out for me? In #216 we completely reworked the way that the cached bundled files works by using the permitted files as a hash for the cached file name. I'm going to close this for now.

If Sean reproduces it, feel free to reopen.

**Closed by cklosowski** 2018-04-10 04:03 UTC
Labels: Bug

**Comment by SDavisMedia** [comment] 2018-04-10 16:53
Can't reproduce it. :+1:
