### ISSUE TITLE
Rebuild modal to be more flexible with purchase links.

### ISSUE THREAD

**Issue by rahilwazir** [easydigitaldownloads/edd-free-downloads#152] opened 2017-02-17 07:25 UTC
The action hooks in `download-modal.php`, passes a parameter `$post`, which holds the current page object instead of each download except single download page.

Right now the download modal have one instance of the template which is reused in runtime, so the `$post` object only usable when viewing single download product.

Real world example:

Add the following action
```
function custom_title_free_downloads_modal( $post ) {
?>
    <h3 style="text-align: center;"><?php echo $post->post_title; ?></h3>
    <hr>
<?php
}
add_action( 'edd_free_downloads_before_modal_form', 'custom_title_free_downloads_modal' );
```
The above hook will add title to the modal, shows the correct title on single download page. On custom page it shows the title of the page instead of each download that are currently being displayed.

![product_title](https://cloud.githubusercontent.com/assets/1818941/23055915/5aeb2ad4-f50a-11e6-8d6f-3ff562a178a4.png)

So it would be better if we make it compatible to work on pages other than single download.

**Comment by dannyb195** [comment] 2017-09-29 17:34
This is confirmed on WP 4.8.2 and EDD FD release/2.2.0 using the 2017 theme

**Comment by dannyb195** [comment] 2017-09-29 19:05
A rather quick solution to this may be to do something like:

<img width="753" alt="screen shot 2017-09-29 at 2 03 44 pm" src="https://user-images.githubusercontent.com/247887/31031709-1043c7fa-a51f-11e7-89f0-acf8ce264f06.png">
<img width="304" alt="screen shot 2017-09-29 at 2 03 52 pm" src="https://user-images.githubusercontent.com/247887/31031710-104521e0-a51f-11e7-9730-0e9d80146639.png">

though this solution does not work for multiple product shortcodes in the same post_content due to the modal being dynamically populated via JS.

**Comment by rahilwazir** [comment] 2017-09-29 19:49
I've had solved this issue, when I reported it (in-short):
**Retrieve the post object using AJAX request, reading the download id from data attribute of the current item.**

But we shouldn't limit it to post title only, user might need the whole post object.
So it would be best if we trigger custom event `jQuery(document).trigger()` for users to listen and manipulate afterwards..

Or we can post whole post object to the attribute as JSON?

I can share source code of my solution if it helps? (too late night, will do tomorrow)

I think its only possible via JS, with PHP we need to create dedicated modal instance for each download item, ain't a good idea.

**Comment by dannyb195** [comment] 2017-10-06 18:42
This issue has identified that the shortcode for free downloads uses the global post ID thus resulting in the page title being pulled as originally reported. @cklosowski and I have decided that a full re-write of the modal is appropriate in this situation to allow for 1. the action `edd_free_downloads_before_modal_form` to behave as intended and 2. to allow for more than 1 shortcode on a page / post.

This should result in the removal of jBox.js from this extension.

**Comment by dannyb195** [comment] 2017-10-12 17:56
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/206/files

**Comment by pippinsplugins** [comment] 2017-10-12 20:21
@dannyb195 I've run it through a few tests and found a few items.

1. File downloads fail completely when the `Bypass if logged in` setting is enabled. The download buttons just don't do anything.

2. The modal window overlay is not filling the whole window:
<img width="1549" alt="screen shot 2017-10-12 at 3 17 51 pm" src="https://user-images.githubusercontent.com/1034109/31517152-abd89146-af60-11e7-80c5-cfb7e52e64c2.png">

3. Email field validation needs to happen with JS. Right now the page reloads and a wp_die() message is shown if you leave the email field empty. First and last name fields seem to validate fine.

4. The required indicator does not show up in the modal when name fields are set to required.

5. We need some CSS love to improve the spacing and alignment. Example:

<img width="691" alt="screen shot 2017-10-12 at 3 21 23 pm" src="https://user-images.githubusercontent.com/1034109/31517298-0f690ac4-af61-11e7-8efd-3c1194bc3176.png">

**Comment by pippinsplugins** [comment] 2017-10-13 18:44
Getting close!

1. This is fixed for products that have a file attached. It fails, however, with products that do not have a file attached. Products without files are supposed to redirect to the confirmation page but right now it triggers a JS error:

Uncaught TypeError: Cannot read property 'split' of null
https://edd.com/wp-content/plugins/edd-free-downloads/assets/js/edd-free-downloads.js?ver=2.1.8 line 173

2. Still happening to me. It's failing on a 903px tall window.

3. Fixed!

4. Fixed!

5. Still looks fugly. Could you show me a screenshot of what yours looks like?

**Comment by dannyb195** [comment] 2017-10-13 19:17
Concerning @pippinsplugins ' above bullet point 5 this is what the logged out modal looks like for me on a 13" MBP. (slightly zoomed out to get the entire modal)

<img width="610" alt="screen shot 2017-10-13 at 2 15 28 pm" src="https://user-images.githubusercontent.com/247887/31562458-25fe7b14-b021-11e7-889d-bfd33dc5cf55.png">

**Comment by pippinsplugins** [comment] 2017-10-16 00:27
@dannyb195 just tested again on a difference machine and still see the issues.

Was a CSS file not added to git perhaps?

Looks like there is also a merge conflict now that will need to be resolved.

**Comment by dannyb195** [comment] 2017-10-16 15:24
My local on 2560x1440 (2017 theme):
![screen shot 2017-10-16 at 10 14 33 am](https://user-images.githubusercontent.com/247887/31620076-eb3b3692-b25b-11e7-97b8-db6206d7c265.png)

Live 152-v2 branch on my 2560x1440 (2014 theme):
![screen shot 2017-10-16 at 10 21 13 am](https://user-images.githubusercontent.com/247887/31620200-40769778-b25c-11e7-83a9-8c674ed332d2.png)

**Comment by pippinsplugins** [comment] 2017-10-16 15:42
@cklosowski can you replicate my issue>

**Comment by cklosowski** [comment] 2017-10-16 19:11
Modal is looking ok to me on `issue/152-v2`
![screen shot 2017-10-16 at 12 10 37 pm](https://user-images.githubusercontent.com/1390124/31630309-15bcdcb8-b26b-11e7-9c24-0d0df21d4a10.png)

**Comment by cklosowski** [comment] 2017-10-16 19:11
This was with a logged out user.

**Comment by cklosowski** [comment] 2017-10-16 19:12
Logged in with ByPass Modal _unchecked_
![screen shot 2017-10-16 at 12 11 38 pm](https://user-images.githubusercontent.com/1390124/31630353-36cdfd74-b26b-11e7-8fd2-5121a7db2f7d.png)

**Comment by cklosowski** [comment] 2017-10-17 23:49
Ok I replicated some CSS issues when the content of the page doesnt' go full height:
![screen shot 2017-10-17 at 4 48 51 pm](https://user-images.githubusercontent.com/1390124/31694805-2e6c39c0-b35b-11e7-97fd-9c27b332a662.png)

**Comment by cklosowski** [comment] 2017-10-17 23:51
@dannyb195 I'm still having an issue in this branch (not `release/2.2.0`) where a logged in user with bypass modal is getting a purchase receipt from an incorrect payment record.

**Comment by cklosowski** [comment] 2017-10-18 23:29
It doesn't appear as this is supporting Price IDs in variable pricing. The only things send to the `get_modal` function are the download ID, and requirements for fields. We also need to send in if the person has a price ID selected.

It's also possible to have a variable priced product with paid and free terms, so the modal would only need to fire on the free item, not the paid one.

**Comment by dannyb195** [comment] 2017-10-19 14:35
per private slack conversation on 10/18 @cklosowski is taking this issues over

**Comment by cklosowski** [comment] 2017-10-19 21:06
@easydigitaldownloads/contributing-devs I think I've got this to a point where I'm ready for some of ya'll to break it :)

**Comment by cklosowski** [comment] 2017-10-19 21:06
Sorry for the mis-tag...that should have been `core-devs` not `contributing-devs`

On a side note, Hello all you contributing devs :)

**Comment by sunnyratilal** [comment] 2017-10-19 22:35
@cklosowski I've tested with a variety of different configurations of the settings and I can't seem to break it. 🎉 

However, this is one thing, when click the `Download Now` button, the AJAX request from EDD is still being triggered and returning `400 Bad Request` (you should see it in the Console).  The error is only caused when clicking the `Download Now` button for a free download; any other purchase button is fine.

**Comment by cklosowski** [comment] 2017-10-19 22:38
Thanks @sunnyratilal I'll try and replicate that.

**Comment by cklosowski** [comment] 2017-10-20 20:48
@sunnyratilal I'm not seeing this 400 error, when you get a minute circle around with me so we can talk though it.

**Comment by cklosowski** [comment] 2017-10-20 22:29
Fixed up a few more bugs in the way that the on-complete handling is done. @sunnyratilal give that another shot, tell me if you are still getting the errors you saw before.

**Comment by sunnyratilal** [comment] 2017-10-23 14:32
@cklosowski Just tested and no longer seeing the errors 👍

**Comment by cklosowski** [comment] 2017-10-23 15:59
@easydigitaldownloads/core-devs This could use a final go through before merging it in.

**Comment by mintplugins** [comment] 2017-10-23 16:22
On mobile I am seeing different behaviour in `master` vs `issue/152 v2`. 

On `master` I get this for the modal:
<img width="214" alt="screen shot 2017-10-23 at 10 20 43 am" src="https://user-images.githubusercontent.com/1638128/31900550-ff2d969c-b7db-11e7-85b6-947ccf8971bd.png">

On `issue/152 v2` I am seeing this:
<img width="212" alt="screen shot 2017-10-23 at 10 17 18 am" src="https://user-images.githubusercontent.com/1638128/31900559-0a05db74-b7dc-11e7-8555-a9cedb6c43cc.png">


For my own reference my testing link is this:
http://edd2.dev/all-access/downloads/licensed-a/#edd-free-download-modal

**Comment by mintplugins** [comment] 2017-10-23 18:15
Confirmed modal works correctly on mobile now (from screenshots above)

**Comment by mintplugins** [comment] 2017-10-23 22:05
Scenarios tested with success 👍 :

**Logged in, modal disabled, multi-price mode:**
Single checked - no payment record, single product in cart
Multiple checked - yes payment record, multiple products in cart

**Logged in, modal disabled, multi-price mode:**
Single checked - yes payment record, single product in cart
Multiple checked - yes payment record, multiple products in cart

**Logged out, modal enabled, multi-price mode:**
Single checked - yes payment record, single products in cart
Multiple checked - yes payment record, multiple products in cart

**Logged out, modal disabled, multi-price mode:**
Single checked - yes payment record, single products in cart
Multiple checked - yes payment record, multiple products in cart

**Comment by mintplugins** [comment] 2017-10-23 22:08
However, the direct download does not seem to do anything as far as I can tell. No errors in console and no URL changes or refreshing:

<img width="373" alt="screen shot 2017-10-23 at 4 07 38 pm" src="https://user-images.githubusercontent.com/1638128/31915628-674e75ae-b80c-11e7-9b8a-d43b064b900e.png">

**Comment by cklosowski** [comment] 2017-10-23 22:16
@mintplugins ok I'll be able to fix that up, as a note, the direct downloads follows a lot of the same logic as the Logged in with modal bypass, but they _will not_ create a payment record (since we cannot know an email address if they don't enter it)

**Comment by cklosowski** [comment] 2017-10-23 23:27
@mintplugins should be all fixed up.

Another testing note, if you could set your Chrome bandwidth throttle to Slow 3G and test out popping the modals that would be awesome too. I noticed that when it was slow it looked like nothing was happening, but this should fix it.

In chrome open the Network panel, and choose the speeds from this menu:
![screen shot 2017-10-23 at 4 27 24 pm](https://user-images.githubusercontent.com/1390124/31917949-13cba6ec-b80f-11e7-9f61-ed04a1df770d.png)

**Comment by dannyb195** [comment] 2017-10-24 14:59
concerning https://github.com/easydigitaldownloads/edd-free-downloads/issues/152#issuecomment-338825622 I did debate putting a spinner in on beforeSend during the ajax call, this wouldn't be difficult if needed.

**Comment by mintplugins** [comment] 2017-10-24 15:28
Confirmed Direct Download is also working now 👍

**Comment by mintplugins** [comment] 2017-10-24 17:23
When you have user registration enabled, it is showing required asterisks. However, I can leave those fields blank and the form submit without requiring me to fill them out.  Related:
https://github.com/easydigitaldownloads/edd-free-downloads/issues/93

**Comment by cklosowski** [comment] 2017-10-24 20:06
I've merged this branch, going to leave it open for now, in case we find anything else while we're going through the rest of the `2.2.0` milestone.

**Comment by cklosowski** [comment] 2017-10-31 00:53
I'm comfortable closing this now.

**Closed by cklosowski** 2017-10-31 00:53 UTC
Labels: Bug
