### ISSUE TITLE
Zip archive contains 404 error code

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#192] opened 2017-09-19 00:02 UTC
If your site uses .htaccess to block direct access to internal files, when Free Downloads tries to add those files, because it does so using the direct url to the internal file (which is blocked), the contents of that file are actually the HTML code of the 404 error page. 

Because of this, we have to find another way to access those internal deliverable file when adding them to the zip archive. Perhaps using the WP Filesystem.

**Comment by mintplugins** [comment] 2017-09-19 00:18
Customer ticket:
https://secure.helpscout.net/conversation/419346899/65391/

**Comment by mintplugins** [comment] 2017-09-20 16:57
Additionally, in testing this, the local vs non-local check for the file location was failing.

My file was hosted locally - but the function `edd_free_downloads_get_host ` was saying the file was hosted foreign.

**Comment by cklosowski** [comment] 2017-10-18 17:31
I'm wondering if it would be helpful to actually use the EDD tokenized file URLs to pull those into a /tmp directory and compress them from there?

That way a file download log would still be produced, we don't have to worry about the access restrictions, and we also get the added benefit of doing it in a space that's usually not persistent.

**Comment by mintplugins** [comment] 2017-10-18 17:40
That's probably a good solution

**Comment by dannyb195** [comment] 2017-10-23 19:17
@mintplugins I cannot reproduce this bug using the current release/2.2.0 branch... can you confirm that this is no longer an issue please. Both "bypass if logged in" and "direct download" are selected on a clean install using Local by Flywheel using apache.

**Comment by pippinsplugins** [comment] 2017-10-31 15:05
I have tested with and without cache enabled.

**Comment by dannyb195** [comment] 2017-10-31 15:11
With my above server config I cannot reproduce what @pippinsplugins has reported (zero bytes files).

<img width="621" alt="screen shot 2017-10-31 at 10 10 44 am" src="https://user-images.githubusercontent.com/247887/32231522-cc8e7b5e-be23-11e7-9847-26dde3a22481.png">

<img width="428" alt="screen shot 2017-10-31 at 10 11 09 am" src="https://user-images.githubusercontent.com/247887/32231536-db459600-be23-11e7-9015-396b211f31e1.png">

**Comment by pippinsplugins** [comment] 2017-10-31 15:17
@dannyb195 can I see a screenshot of the following please?

1. The product edit screen showing the download files
2. Downloads > Settings > Extensions > Free Downloads
3. Downloads > Settings > Misc > File Downloads

**Comment by dannyb195** [comment] 2017-10-31 15:24
1.
<img width="1196" alt="screen shot 2017-10-31 at 10 21 01 am" src="https://user-images.githubusercontent.com/247887/32232081-3c4a4184-be25-11e7-910a-9ef20fb8e422.png">

2.
<img width="824" alt="screen shot 2017-10-31 at 10 22 32 am" src="https://user-images.githubusercontent.com/247887/32232188-7bd6e87a-be25-11e7-9d19-736828019607.png">

3. 
<img width="1084" alt="screen shot 2017-10-31 at 10 23 44 am" src="https://user-images.githubusercontent.com/247887/32232246-9f89353e-be25-11e7-9eb8-a7d8cae95f42.png">

**Comment by pippinsplugins** [comment] 2017-10-31 15:27
@dannyb195 try again with `Bypass if logged in` unchecked. Also purge the cache.

**Comment by pippinsplugins** [comment] 2017-10-31 15:29
No matter what configuration I try for Free Downloads, the files in the zip archive are always zero bytes.

**Comment by pippinsplugins** [comment] 2017-10-31 15:30
I've also tried with and without Dropbox / Amazon S3 activated.

**Comment by dannyb195** [comment] 2017-10-31 16:38
With `bypass if logged in` _unchecked_ I am redirected to the core EDD confirmation page even with the `On-Complete Handler` set to `auto download`. Tested both logged in and logged out.

**Comment by cklosowski** [comment] 2017-10-31 16:38
@dannyb195 did you have a file attached to that item? In the event that auto-download is enabled, but there are no files on that specific download it will go to the purchase confirmatoin

**Comment by pippinsplugins** [comment] 2017-10-31 16:48
@cklosowski closer but still incorrect behavior.

My zip file only contains one file now instead of two:

<img width="563" alt="screen shot 2017-10-31 at 11 48 38 am" src="https://user-images.githubusercontent.com/1034109/32236892-799232a2-be31-11e7-8b60-c58b8aa397e1.png">
<img width="1169" alt="screen shot 2017-10-31 at 11 48 43 am" src="https://user-images.githubusercontent.com/1034109/32236893-79a767b2-be31-11e7-9452-6415d2f7a8c1.png">

**Comment by cklosowski** [comment] 2017-10-31 16:50
Interesting, mine all contain the correct ones. I tihnk I was testing with variable pricing and price assignments for the files...i'll go single price and give that a whirl.

**Comment by cklosowski** [comment] 2017-10-31 17:13
We've decided to close this. Something is going on with pippin's tests, but everything oethers can do aren't replicating this. we can open a new issue if this arrises more.

**Closed by cklosowski** 2017-10-31 17:13 UTC
Labels: Bug, in progress, Needs Reporter Feedback
