### ISSUE TITLE
Auto Download feature causing ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#41] opened 2016-01-11 20:50 UTC
[Customer reported](https://secure.helpscout.net/conversation/158982281/24879/?folderId=180504) this and I've been able to replicate it, though @SDavisMedia was not able to replicate it. Tested in EDD 2.4.10 and 2.5.3 and it happens in both. I'm on Free Downloads 1.1.1 and so is customer.

When Auto Download is enabled and someone fills out the form in the modal and submits, the file doesn't download and the browser shows an invalid response and/or does a redirect loop. (Redirect loop reported by customer).

This seems to happen with "Redirect on Download" both on and off.

When the EDD setting for Download Method is set to 'forced', I'm sent an index.php file with the following notices in it:
```
<br />
<b>Notice</b>:  Undefined variable: file_path in <b>/web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php</b> on line <b>198</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php:198) in <b>/web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php</b> on line <b>198</b><br />
<br />
<b>Notice</b>:  Undefined variable: file_path in <b>/web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php</b> on line <b>203</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php:198) in <b>/web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php</b> on line <b>203</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php:198) in <b>/web/brand-new-edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php</b> on line <b>295</b><br />
```

Product config is standard, not bundle, with just a single download file attached. Nothing special. Only two plugins active are EDD and Free Downloads.

@ghost1227 let me know if you need any extra info.

**Comment by pippinsplugins** [comment] 2016-01-11 20:53
I bet it's related to this:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4113

**Comment by SDavisMedia** [comment] 2016-01-12 05:38
Okay it looks like I have a case of this now. I still can't replicate it myself but I have a user who's either getting sent to an [error page](http://glui.me/?i=hibzczrlxyotll6/2016-01-11_at_9.36_PM.png/) or when it does work, it's downloading an index.php file. https://secure.helpscout.net/conversation/159358825/24986/?folderId=321418

WP 4.4.1, EDD 2.5.3, Free Downloads 1.1.1

**Comment by mindctrl** [comment] 2016-01-12 14:19
@SDavisMedia in your tests yesterday, which version of WP were you on?

**Comment by pippinsplugins** [comment] 2016-01-12 14:24
@ghost1227 We've got another report of this today.  Can you work on it please?

**Comment by dearestdebi** [comment] 2016-01-12 16:06
I just purchased the free download option for EDD. I set up an example which is working on this page.. DearestDebi.com/coupons which is a blog PAGE. (Click the pink download arrow for download button) 

I've replicated the same set up but for a blog POST and it's producing an error. (Click the SECOND pink download button to see download button)

Just figured I would share what I've come across if it hadn't already been brought up.

**Comment by dearestdebi** [comment] 2016-01-12 16:07
Oops the blog post link is dearestdebi.com/not-another-bonnet

**Comment by mindctrl** [comment] 2016-01-12 16:10
@dearestdebi thanks for the info! We'll dig into this and get it fixed ASAP.

**Comment by SDavisMedia** [comment] 2016-01-12 16:19
@mindctrl I was on 4.4.2 alpha.

@dearestdebi Thanks for stopping by to report. Your support ticket is the one I linked in my last comment.

**Comment by dearestdebi** [comment] 2016-01-12 23:59
Any resolve to this issue?

**Comment by SDavisMedia** [comment] 2016-01-13 00:14
Hi @dearestdebi. Please reserve the GitHub Issues for development and testing discussion. You and I can continue to communicate in your support ticket. As of right now, this has not been fixed. You will be informed as soon as it is addressed.

**Comment by dearestdebi** [comment] 2016-01-13 00:51
Understood. Thanks

**Comment by ghost1227** [comment] 2016-01-13 16:15
Is there any commonality to the affected sites? A particular webhost or server configuration perhaps? Also, is this something that has suddenly occurred (ie, a new issue caused by update), or are the users experiencing it all new users?

**Closed** 2016-01-13 18:56 UTC
Labels: bug, in progress
