### ISSUE TITLE
Download button doesn't return if modal is dismissed

### ISSUE THREAD

**Issue by samglover** [easydigitaldownloads/edd-free-downloads#90] opened 2016-09-26 13:36 UTC
When someone clicks the Download Now button, the modal pops up and the button on the underlying page disappears. But if the user dismisses the modal, either by clicking on the background page or by clicking the X, the Download Now button stays gone and it's not clear how one would get it back.

Example: https://lawyerist.com/downloads/law-firm-website-design-guide/

The button should return when the modal is dismissed.

**Comment by ghost1227** [comment] 2016-09-26 15:27
Closing as duplicate of #79 and pinging @michaelbeil (this update was supposed to go out last week!)

**Closed by ghost1227** 2016-09-26 15:27 UTC
Labels: Bug, Duplicate
